config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :calls
  resources :registers

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/call.rb
class Call < ApplicationRecord
  belongs_to  :register
end

app/models/register.rb
class Register < ApplicationRecord
  has_many :call

  validates :correo, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  validates :comuna, :calle, :numero, :encargado, :telefono, :correo, :contenedores, :establecimiento, :presence => true
  validates :telefono, length: { minimum: 7 }
  validates :telefono, length: { maximum: 9 }

  validates_uniqueness_of :calle, scope: [:numero, :comuna], :case_sensitive => false

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/calls_controller.rb
class CallsController < ApplicationController
  before_action :set_call, only: [:show, :edit, :update, :destroy]

  # GET /calls
  # GET /calls.json
  def index

    @comunas = Register.distinct.pluck(:comuna)
    @registers = Register.all
    if params[:filtro_comuna].blank?
      @calls = Call.all
    else
      @registers = Register.where(:comuna => params[:filtro_comuna])
      @calls = []
      @registers.each do |r|
        @call_r = Call.where(:register_id => r.id)
        @calls = @calls + @call_r
      end
    end
  end

  # GET /calls/1
  # GET /calls/1.json
  def show
  end

  # GET /calls/new
  def new
    @comunas = Register.distinct.pluck(:comuna)
    @registers = Register.all

    @call = Call.new
    if params[:filtro_comuna].blank?
      @calls = Call.all
    else
      @registers = Register.where(:comuna => params[:filtro_comuna]).map{ |r| [r.calle + ' ' + r.numero.to_s, r.id] }

    end
  end

  # GET /calls/1/edit
  def edit
  end

  # POST /calls
  # POST /calls.json
  def create
    @call = Call.new(call_params)
    @call.register_id =  params[:register_id]

    respond_to do |format|
      if @call.save
        format.html { redirect_to @call, notice: 'Call was successfully created.' }
        format.json { render :show, status: :created, location: @call }
      else
        format.html { render :new }
        format.json { render json: @call.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calls/1
  # PATCH/PUT /calls/1.json
  def update
    respond_to do |format|
      if @call.update(call_params)
        format.html { redirect_to @call, notice: 'Call was successfully updated.' }
        format.json { render :show, status: :ok, location: @call }
      else
        format.html { render :edit }
        format.json { render json: @call.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calls/1
  # DELETE /calls/1.json
  def destroy
    @call.destroy
    respond_to do |format|
      format.html { redirect_to calls_url, notice: 'Call was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def call_params
      params.require(:call).permit(:fecha_llamado, :fecha_retiro, :register_id, :status)
    end

    def set_call
      @call = Call.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def call_params
      params.require(:call).permit(:fecha_llamado, :fecha_retiro, :status)
    end
end

app/controllers/registers_controller.rb
class RegistersController < ApplicationController
  before_action :set_register, only: [:show, :edit, :update, :destroy]

  # GET /registers
  # GET /registers.json
  def index
    @registers = Register.all
  end

  # GET /registers/1
  # GET /registers/1.json
  def show
  end

  # GET /registers/new
  def new
    @register = Register.new
  end

  # GET /registers/1/edit
  def edit
  end

  # POST /registers
  # POST /registers.json
  def create
    atributes = {
      comuna: register_params[:comuna],
      calle: register_params[:calle],
      numero: register_params[:numero]
    }
    @register = Register.where(atributes).first
    @register = Register.new(register_params) #unless @register

    respond_to do |format|
      if @register.save
        format.html { redirect_to @register, notice: 'Register was successfully created.' }
        format.json { render :show, status: :created, location: @register }
      else
        format.html { render :new }
        format.json { render json: @register.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /registers/1
  # PATCH/PUT /registers/1.json
  def update
    respond_to do |format|
      if @register.update(register_params)
        format.html { redirect_to @register, notice: 'Register was successfully updated.' }
        format.json { render :show, status: :ok, location: @register }
      else
        format.html { render :edit }
        format.json { render json: @register.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registers/1
  # DELETE /registers/1.json
  def destroy
    @register.destroy
    respond_to do |format|
      format.html { redirect_to registers_url, notice: 'Register was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_register
      @register = Register.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def register_params
      params.require(:register).permit(:comuna, :calle, :numero, :encargado, :telefono, :correo, :contenedores, :establecimiento)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calls_helper.rb
module CallsHelper
end

app/helpers/registers_helper.rb
module RegistersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/calls/_form.html.erb
<%= form_with(model: call, local: true) do |form| %>
  <% if call.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(call.errors.count, "error") %> prohibited this call from being saved:</h2>

      <ul>
      <% call.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="container-fluid">
    <%= simple_form_for @call do |c| %>
      <%= select_tag(:register_id, options_for_select(@registers), :prompt => "Seleccionar una direccion") %>
      <p> </p>
      <%= c.label :fecha_llamado %>
      <%= c.datetime_select :fecha_llamado, id: :call_fecha_llamado %>
      <p> </p>
      <%= c.label :fecha_retiro %>
      <%= c.datetime_select :fecha_retiro, id: :call_fecha_retiro  %>
      <p> </p>
      <%= form.label :status %>
      <%= form.select :status, [['Urgente', 'Urgente'],['En proceso','En proceso'],['Normal','Normal']], :prompt => "Estado"%>
      <p> </p>
      <p> </p>
      <%= c.button :submit, 'Crear' %>

    <% end %>

  </div>


<% end %>

app/views/calls/edit.html.erb
<h1>Editing Call</h1>

<%= render 'form', call: @call %>

<%= link_to 'Show', @call %> |
<%= link_to 'Back', calls_path %>

app/views/calls/index.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron text-center">
 <h1>INGRESO DE LLAMADAS</h1>
 <%= button_to "Crear Llamada", new_call_path, :id => "open-contacts-dialog-btn",
       :class => "inbox-sf-add-btn tip", :method => :get %>
</div>


<div class = "container text-center">
  <div class="dropdown">
    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
      Filtrar por comuna
      <span class="caret"></span>
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenu1">
      <% @comunas.each do |comuna| %>
        <li>
          <%= link_to comuna, calls_path(filtro_comuna: comuna), class: "link" %>
        </li>
      <% end %>
    </div>
  </div>
</div>
<br>


<div class="container">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Fella Llamado</th>
        <th>Fecha Retiro</th>
        <th>Estado</th>
        <th>Comuna</th>
        <th>Calle</th>
        <th>Número</th>
      </tr>
    </thead>
    <tbody>
      <% @calls.each do |call| %>
        <tr>
          <td><%= call.fecha_llamado %></td>
          <td><%= call.fecha_retiro %></td>
          <td><%= call.status %></td>
          <td><%= call.register.comuna %></td>
          <td><%= call.register.calle %></td>
          <td><%= call.register.numero %></td>
          <td><%= link_to 'Show', call %></td>
          <td><%= link_to 'Edit', edit_call_path(call) %></td>
          <td><%= link_to 'Destroy', call, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>
<div class = "container text-center">
  <%= link_to 'Atrás', welcome_index_path, class: "btn btn-default btn-lg"  %>
</div>

app/views/calls/new.html.erb
<div class = "jumbotron text-center">
  <h1>Nueva Llamada</h1>
</div>


<div class = "container text-center">

  <div class="dropdown">
    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
      Comunas
      <span class="caret"></span>
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenu1">
      <% @comunas.each do |comuna| %>
        <li>
          <%= link_to comuna, new_call_path(filtro_comuna: comuna), class: "link" %>
        </li>
      <% end %>
    </div>
  </div>
<p></p>

<%if !params[:filtro_comuna].blank? %>
  <%= render 'form', call: @call %>
<% end %>

<br>

<%= link_to 'Atrás', calls_path, class: "btn btn-default btn-lg"  %>

</div>

app/views/calls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fecha llamado:</strong>
  <%= @call.fecha_llamado %>
</p>

<p>
  <strong>Fecha retiro:</strong>
  <%= @call.fecha_retiro %>
</p>

<p>
  <strong>Status:</strong>
  <%= @call.status %>
</p>

<%= link_to 'Edit', edit_call_path(@call) %> |
<%= link_to 'Back', calls_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CristoroApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">CRISTORO</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li ><a href="/registers">Registrar Punto</a></li>
            <li><a href="/calls">Ingresar Llamada</a></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <%= yield %>

  </body>
</html>

app/views/registers/_form.html.erb
<div class = "container text-center">
  <%= form_with(model: register, local: true) do |form| %>
    <% if register.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(register.errors.count, "error") %> encontrados</h2>

        <ul>
        <% register.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>

        </ul>
      </div>
    <% end %>

    <div class = "field">
        <%= form.select :comuna, [['Alhué','Alhué'],['Buin','Buin'],['Calera de Tango','Calera de Tango'],
        ['Cerrillos','Cerrillos'],['Cerro Navia','Cerro Navia'],['Colina','Colina'],
        ['Conchalí','Conchalí'],['Curacaví','Curacaví'],['El Bosque','El Bosque'],
        ['El Monte','El Monte'],['Estación Central','Estación Central'],['Huechuraba','Huechuraba'],
        ['Independencia','Independencia'],['Isla de Maipo','Isla de Maipo'],['La Cisterna','La Cisterna'],
        ['La Florida','La Florida'],['La Granja','La Granja'],['La Pintana','La Pintana'],
        ['La Reina','La Reina'],['Lampa','Lampa'],['Las Condes','Las Condes'],
        ['Lo Barnechea','Lo Barnechea'],['Lo Espejo','Lo Espejo'],['Lo Prado','Lo Prado'],
        ['Macul','Macul'],['Maipú','Maipú'],['María Pinto','María Pinto'],
        ['Melipilla','Melipilla'],['Ñuñoa','Ñuñoa'],['Padre Hurtado','Padre Hurtado'],
        ['Paine','Paine'],['Pedro Aguirre Cerda','Pedro Aguirre Cerda'],['Peñaflor','Peñaflor'],
        ['Peñalolén','Peñalolén'],['Pirque','Pirque'],['Providencia','Providencia'],
        ['Pudahuel','Pudahuel'],['Puente Alto','Puente Alto'],['Quilicura','Quilicura'],
        ['Quinta Normal','Quinta Normal'],['Recoleta','Recoleta'],['Renca','Renca'],
        ['San Bernardo','San Bernardo'],['San Joaquín','San Joaquín'],['San José de Maipo','San José de Maipo'],
        ['San Miguel','San Miguel'],['San Pedro','San Pedro'],['San Ramón','San Ramón'],
        ['Santiago','Santiago'],['Talagante','Talagante'],['Til Til','Til Til'],
        ['Vitacura','Vitacura']], :prompt => "Seleccionar una comuna"%>
    </div>


    <div class="field">
      <%= form.label :calle %>
      <%= form.text_field :calle, id: :register_calle %>
    </div>

    <div class="field">
      <%= form.label :numero, 'Número' %>
      <%= form.number_field :numero, id: :register_numero %>
    </div>

    <div class="field">
      <%= form.label :encargado %>
      <%= form.text_field :encargado, id: :register_encargado %>
    </div>

    <div class="field">
      <%= form.label :telefono, 'Teléfono +56 9 ' %>
      <%= form.number_field :telefono, id: :register_telefono %>
    </div>

    <div class="field">
      <%= form.label :correo %>
      <%= form.text_field :correo, id: :register_correo, placeholder: 'user@domain.com' %>

    </div>

    <div class="field">
      <%= form.label :contenedores %>
      <%= form.number_field :contenedores, id: :register_contenedores %>
    </div>

    <div class = "field">
        <%= form.select :establecimiento, [['Casa','Casa'],['Edificio','Edificio'],['Club Deportivo','Club Deportivo'],
        ['Centro de Eventos','Centro de Eventos']], :prompt => "Seleccionar tipo de establecimiento"%>
    </div>


      <div class="actions">
        <%= form.submit "Crear"%>
      </div>

  <% end %>
</div>

app/views/registers/edit.html.erb
<h1>Editing Register</h1>

<%= render 'form', register: @register %>

<%= link_to 'Show', @register %> |
<%= link_to 'Back', registers_path %>

app/views/registers/index.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron text-center">
 <h1>PUNTOS DE RECOLECCIÓN</h1>
 <%= button_to "Crear Punto", new_register_path, :id => "open-contacts-dialog-btn",
       :class => "inbox-sf-add-btn tip", :method => :get %>
</div>
<div class="container">

  <table class="table table-hover">
    <thead>
      <tr>
        <th>Comuna</th>
        <th>Calle</th>
        <th>Numero</th>
        <th>Encargado</th>
        <th>Telefono</th>
        <th>Correo</th>
        <th>Contenedores</th>
        <th>Establecimiento</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @registers.each do |register| %>
        <tr>
          <td><%= register.comuna %></td>
          <td><%= register.calle %></td>
          <td><%= register.numero %></td>
          <td><%= register.encargado %></td>
          <td><%= register.telefono %></td>
          <td><%= register.correo %></td>
          <td><%= register.contenedores %></td>
          <td><%= register.establecimiento %></td>
          <td><%= link_to 'Show', register %></td>
          <td><%= link_to 'Edit', edit_register_path(register) %></td>
          <td><%= link_to 'Destroy', register, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>
<div class = "container text-center">
  <%= link_to 'Atrás', welcome_index_path, class: "btn btn-default btn-lg" %>
</div>

app/views/registers/new.html.erb
<div class = "jumbotron text-center">
  <h1>Crear Punto</h1>
</div>


<%= render 'form', register: @register %>


<div class = "container text-center">
  <%= link_to 'Atrás', registers_path, class: "btn btn-default btn-lg"   %>
</div>

app/views/registers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comuna:</strong>
  <%= @register.comuna %>
</p>

<p>
  <strong>Calle:</strong>
  <%= @register.calle %>
</p>

<p>
  <strong>Numero:</strong>
  <%= @register.numero %>
</p>

<p>
  <strong>Encargado:</strong>
  <%= @register.encargado %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @register.telefono %>
</p>

<p>
  <strong>Correo:</strong>
  <%= @register.correo %>
</p>

<p>
  <strong>Contenedores:</strong>
  <%= @register.contenedores %>
</p>

<p>
  <strong>Establecimiento:</strong>
  <%= @register.establecimiento %>
</p>

<%= link_to 'Edit', edit_register_path(@register) %> |
<%= link_to 'Back', registers_path %>

app/views/welcome/index.html.erb
<!--<%= link_to "Registrar Punto", registers_path %>
<%= link_to "Ingresar Llamada", calls_path %>
-->

<div class="jumbotron text-center">
 <h1>CRISTORO</h1>
 <br>
 <h3>Plataforma para registros de reciclaje.</h3>
</div>